import { Technology, LogType } from "@/types";

export const cortexXdr: Technology = {
  id: "cortex-xdr",
  name: "Cortex XDR",
  description: "Extended detection and response platform providing endpoint protection, detection, and investigation capabilities with rich telemetry data",
  vendor: "Palo Alto Networks",
  openSource: false,
  officialDocs: "https://docs-cortex.paloaltonetworks.com/r/Cortex-XDR",
  logo: "/logos/paloalto.svg",
  categories: ["Security", "EDR", "Endpoint"],
  logTypes: [
    {
      id: "endpoint-events",
      name: "Endpoint Events",
      description: "Comprehensive endpoint telemetry including process, file, network, and registry events",
      defaultPath: "Cortex XDR Console / API",
    },
    {
      id: "alerts",
      name: "Alerts",
      description: "Security alerts generated by analytics, BIOC rules, and threat detection",
      defaultPath: "Cortex XDR Console / API",
    },
  ],
  defaultPaths: {
    console: "https://<tenant>.xdr.paloaltonetworks.com",
    api: "https://api-<tenant>.xdr.paloaltonetworks.com",
    syslog: "SIEM forwarding via Broker VM",
  },
  contribution: {
    createdAt: "2026-01-03",
    createdBy: "admin",
    updatedAt: "2026-01-03",
    updatedBy: "admin",
    contributors: ["admin"],
    validated: false,
  },
};

export const cortexXdrEndpointEvents: LogType = {
  id: "endpoint-events",
  technologyId: "cortex-xdr",
  name: "Endpoint Events",
  description: "Rich endpoint telemetry collected by Cortex XDR agents including process executions, file operations, network connections, registry modifications, and behavioral data for threat detection and forensic investigation",
  quickFacts: {
    defaultPathLinux: "Cortex XDR Console > Investigation > Query Center",
    defaultPathDocker: "N/A - Agent-based collection",
    defaultFormat: "JSON (via API) / CEF (via SIEM forwarding)",
    jsonNative: true,
    rotation: "Cloud-based retention (configurable 30-180 days)",
  },
  paths: {
    linux: [
      {
        distro: "Agent Logs",
        path: "/var/log/traps/",
        note: "Local agent logs (limited data, full telemetry in cloud)",
      },
    ],
    windows: [
      {
        distro: "Agent Logs",
        path: "C:\\ProgramData\\Cyvera\\Logs\\",
        note: "Local agent diagnostic logs",
      },
    ],
    cloud: [
      {
        provider: "Cortex XDR Console",
        path: "Investigation > Query Center",
      },
      {
        provider: "Cortex XDR API",
        path: "POST /public_api/v1/xql/start_xql_query",
      },
      {
        provider: "Cortex Data Lake",
        path: "Cortex Data Lake > Explore > XDR",
      },
      {
        provider: "SIEM Forwarding",
        path: "Settings > Integrations > External Applications > Syslog",
      },
    ],
  },
  formats: [
    {
      id: "json",
      name: "JSON Format (API/XQL)",
      isDefault: true,
      structure: "Nested JSON with event-specific fields based on event type",
      example: `{
  "event_id": "abc123def456",
  "event_type": "PROCESS",
  "event_sub_type": "PROCESS_START",
  "event_timestamp": 1704200000000,
  "endpoint_id": "e1f2a3b4c5d6",
  "endpoint_name": "WORKSTATION-01",
  "endpoint_domain": "corp.local",
  "endpoint_os": "Windows 10",
  "agent_version": "8.2.0.12345",
  "action_process_image_name": "powershell.exe",
  "action_process_image_path": "C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe",
  "action_process_image_sha256": "a1b2c3d4e5f6...",
  "action_process_command_line": "powershell.exe -ExecutionPolicy Bypass -File script.ps1",
  "action_process_signature_vendor": "Microsoft Corporation",
  "action_process_signature_status": "SIGNED",
  "actor_process_image_name": "cmd.exe",
  "actor_process_image_path": "C:\\\\Windows\\\\System32\\\\cmd.exe",
  "actor_process_pid": 4532,
  "actor_primary_user_sid": "S-1-5-21-...",
  "actor_primary_username": "jsmith",
  "causality_actor_process_image_name": "explorer.exe",
  "causality_actor_causality_id": "xyz789"
}`,
    },
    {
      id: "cef",
      name: "CEF Format (SIEM Forwarding)",
      isDefault: false,
      structure: "Common Event Format for SIEM integration via Broker VM",
      example: `CEF:0|Palo Alto Networks|Cortex XDR|8.2|PROCESS|Process Execution|5|rt=1704200000000 dhost=WORKSTATION-01 duser=jsmith fname=powershell.exe fpath=C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe cs1=powershell.exe -ExecutionPolicy Bypass -File script.ps1 cs1Label=CommandLine fileHash=a1b2c3d4e5f6...`,
    },
    {
      id: "leef",
      name: "LEEF Format (IBM QRadar)",
      isDefault: false,
      structure: "Log Event Extended Format for QRadar integration",
      example: `LEEF:2.0|Palo Alto Networks|Cortex XDR|8.2|PROCESS|devTime=1704200000000\tdevTimeFormat=epoch\tdst=WORKSTATION-01\tusrName=jsmith\tfileName=powershell.exe\tfilePath=C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`,
    },
  ],
  fields: [
    {
      name: "event_id",
      type: "string",
      description: "Unique identifier for the event",
      example: "abc123def456",
    },
    {
      name: "event_type",
      type: "string",
      description: "Primary event type category",
      example: "PROCESS",
      enum: ["PROCESS", "FILE", "NETWORK", "REGISTRY", "INJECTION", "LOAD_IMAGE", "EVENT_LOG", "SCHEDULED_TASK"],
    },
    {
      name: "event_sub_type",
      type: "string",
      description: "Specific event subtype",
      example: "PROCESS_START",
      enum: [
        "PROCESS_START", "PROCESS_END", "PROCESS_BLOCKED",
        "FILE_CREATE", "FILE_WRITE", "FILE_DELETE", "FILE_RENAME", "FILE_READ",
        "NETWORK_CONNECTION", "NETWORK_LISTEN", "NETWORK_DNS",
        "REGISTRY_SET_VALUE", "REGISTRY_CREATE_KEY", "REGISTRY_DELETE_VALUE",
        "INJECTION_SHELLCODE", "INJECTION_PROCESS_HOLLOWING",
        "MODULE_LOAD"
      ],
    },
    {
      name: "event_timestamp",
      type: "integer",
      description: "Event timestamp in epoch milliseconds",
      example: 1704200000000,
      unit: "milliseconds",
    },
    {
      name: "endpoint_id",
      type: "string",
      description: "Unique identifier for the endpoint",
      example: "e1f2a3b4c5d6",
    },
    {
      name: "endpoint_name",
      type: "string",
      description: "Hostname of the endpoint",
      example: "WORKSTATION-01",
    },
    {
      name: "endpoint_domain",
      type: "string",
      description: "Domain the endpoint belongs to",
      example: "corp.local",
    },
    {
      name: "endpoint_os",
      type: "string",
      description: "Operating system of the endpoint",
      example: "Windows 10",
      enum: ["Windows 7", "Windows 10", "Windows 11", "Windows Server 2016", "Windows Server 2019", "Windows Server 2022", "macOS", "Linux"],
    },
    {
      name: "endpoint_os_version",
      type: "string",
      description: "Full OS version string",
      example: "10.0.19045",
    },
    {
      name: "agent_version",
      type: "string",
      description: "Version of the Cortex XDR agent",
      example: "8.2.0.12345",
    },
    {
      name: "action_process_image_name",
      type: "string",
      description: "Name of the process being executed (target process)",
      example: "powershell.exe",
    },
    {
      name: "action_process_image_path",
      type: "string",
      description: "Full path to the process executable",
      example: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    },
    {
      name: "action_process_image_sha256",
      type: "string",
      description: "SHA256 hash of the process executable",
      example: "a1b2c3d4e5f67890abcdef1234567890abcdef1234567890abcdef1234567890",
    },
    {
      name: "action_process_command_line",
      type: "string",
      description: "Full command line of the executed process",
      example: "powershell.exe -ExecutionPolicy Bypass -File script.ps1",
    },
    {
      name: "action_process_pid",
      type: "integer",
      description: "Process ID of the action process",
      example: 1234,
    },
    {
      name: "action_process_signature_vendor",
      type: "string",
      description: "Vendor name from the digital signature",
      example: "Microsoft Corporation",
    },
    {
      name: "action_process_signature_status",
      type: "string",
      description: "Digital signature verification status",
      example: "SIGNED",
      enum: ["SIGNED", "UNSIGNED", "INVALID_SIGNATURE", "REVOKED", "EXPIRED"],
    },
    {
      name: "actor_process_image_name",
      type: "string",
      description: "Name of the parent process that initiated the action",
      example: "cmd.exe",
    },
    {
      name: "actor_process_image_path",
      type: "string",
      description: "Full path to the parent process",
      example: "C:\\Windows\\System32\\cmd.exe",
    },
    {
      name: "actor_process_pid",
      type: "integer",
      description: "Process ID of the parent/actor process",
      example: 4532,
    },
    {
      name: "actor_process_command_line",
      type: "string",
      description: "Command line of the parent process",
      example: "cmd.exe /c start.bat",
    },
    {
      name: "actor_primary_user_sid",
      type: "string",
      description: "Windows SID of the user running the process",
      example: "S-1-5-21-1234567890-1234567890-1234567890-1001",
    },
    {
      name: "actor_primary_username",
      type: "string",
      description: "Username running the process",
      example: "jsmith",
    },
    {
      name: "causality_actor_process_image_name",
      type: "string",
      description: "Root process that initiated the causality chain",
      example: "explorer.exe",
    },
    {
      name: "causality_actor_causality_id",
      type: "string",
      description: "Unique identifier linking related events in a causality chain",
      example: "xyz789abc123",
    },
    {
      name: "action_file_name",
      type: "string",
      description: "Name of the file involved in file events",
      example: "malware.exe",
    },
    {
      name: "action_file_path",
      type: "string",
      description: "Full path of the file involved in file events",
      example: "C:\\Users\\jsmith\\Downloads\\malware.exe",
    },
    {
      name: "action_file_sha256",
      type: "string",
      description: "SHA256 hash of the file",
      example: "b2c3d4e5f67890abcdef1234567890abcdef1234567890abcdef1234567890ab",
    },
    {
      name: "action_file_size",
      type: "integer",
      description: "Size of the file in bytes",
      example: 524288,
      unit: "bytes",
    },
    {
      name: "action_remote_ip",
      type: "ip",
      description: "Remote IP address for network events",
      example: "203.0.113.50",
    },
    {
      name: "action_remote_port",
      type: "integer",
      description: "Remote port for network events",
      example: 443,
    },
    {
      name: "action_local_ip",
      type: "ip",
      description: "Local IP address for network events",
      example: "192.168.1.100",
    },
    {
      name: "action_local_port",
      type: "integer",
      description: "Local port for network events",
      example: 54321,
    },
    {
      name: "action_network_protocol",
      type: "string",
      description: "Network protocol used",
      example: "TCP",
      enum: ["TCP", "UDP", "ICMP"],
    },
    {
      name: "dns_query_name",
      type: "string",
      description: "DNS query hostname",
      example: "malicious-domain.com",
    },
    {
      name: "action_registry_key_name",
      type: "string",
      description: "Registry key path for registry events",
      example: "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run",
    },
    {
      name: "action_registry_value_name",
      type: "string",
      description: "Registry value name",
      example: "MalwareStartup",
    },
    {
      name: "action_registry_data",
      type: "string",
      description: "Data written to the registry value",
      example: "C:\\ProgramData\\malware.exe",
    },
    {
      name: "module_sha256",
      type: "string",
      description: "SHA256 hash of loaded module/DLL",
      example: "c3d4e5f67890abcdef1234567890abcdef1234567890abcdef1234567890abcd",
    },
    {
      name: "module_path",
      type: "string",
      description: "Path to the loaded module/DLL",
      example: "C:\\Windows\\System32\\kernel32.dll",
    },
  ],
  parsing: {
    grok: {
      json: `# XQL queries return JSON - use JSON parser
# Example XQL: dataset = xdr_data | filter event_type = PROCESS`,
    },
    regex: {
      cef: `CEF:\\d+\\|Palo Alto Networks\\|Cortex XDR\\|(?P<version>[^|]+)\\|(?P<event_type>[^|]+)\\|(?P<event_name>[^|]+)\\|(?P<severity>\\d+)\\|(?P<extensions>.*)`,
    },
    examples: {
      splunk: `# Cortex XDR to Splunk via SIEM Integration
[cortex:xdr:endpoint]
TIME_FORMAT = %s%3N
TIME_PREFIX = rt=
SHOULD_LINEMERGE = false
KV_MODE = none
TRUNCATE = 65535

# Search for process events
index=cortex_xdr sourcetype="cortex:xdr:endpoint" event_type=PROCESS
| stats count by action_process_image_name, actor_primary_username, endpoint_name

# Hunt for PowerShell with suspicious flags
index=cortex_xdr sourcetype="cortex:xdr:endpoint" action_process_image_name="powershell.exe"
| search action_process_command_line IN ("*-enc*", "*-ExecutionPolicy Bypass*", "*-nop*", "*IEX*", "*DownloadString*")
| table _time, endpoint_name, actor_primary_username, action_process_command_line`,
      logstash: `input {
  http {
    port => 8080
    codec => json
    type => "cortex_xdr"
  }
}

filter {
  if [type] == "cortex_xdr" {
    date {
      match => ["event_timestamp", "UNIX_MS"]
      target => "@timestamp"
    }

    # Normalize event types
    mutate {
      lowercase => ["event_type", "event_sub_type"]
    }

    # Extract filename from path
    if [action_process_image_path] {
      grok {
        match => { "action_process_image_path" => ".*[/\\\\](?<action_process_filename>[^/\\\\]+)$" }
      }
    }

    # GeoIP for remote connections
    if [action_remote_ip] {
      geoip {
        source => "action_remote_ip"
        target => "remote_geo"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "cortex-xdr-endpoint-%{+YYYY.MM.dd}"
  }
}`,
      cribl: `# Cribl Stream Pipeline for Cortex XDR
filter: sourcetype=='cortex:xdr:endpoint'
functions:
  - id: eval
    filter: "true"
    conf:
      add:
        - name: _time
          value: event_timestamp/1000
  - id: rename
    conf:
      renameExpr:
        - currentName: action_process_image_name
          newName: process_name
        - currentName: actor_primary_username
          newName: user
        - currentName: endpoint_name
          newName: host
  - id: sampling
    filter: event_type=='NETWORK' && action_remote_port==443
    conf:
      rate: 10`,
      qradar: `# QRadar integration via Cortex XDR SIEM connector
Log Source Type: Palo Alto Cortex XDR
Protocol Type: Syslog (CEF)
Log Source Identifier: cortex-xdr

# Custom properties for XDR events
event_type -> EventCategory
action_process_image_name -> FileName
action_process_command_line -> CommandLine
actor_primary_username -> Username
endpoint_name -> SourceHostName`,
    },
  },
  configuration: {
    enableLogging: {
      description: "Configure Cortex XDR data collection profiles",
      example: `# Via Cortex XDR Console
# Navigate to: Settings > Endpoint Security > Profiles > Agent Settings

# Enable comprehensive data collection:
1. Process Execution Data: Enable
2. Network Data Collection: Enable
3. File Access Monitoring: Enable
4. Registry Monitoring: Enable (Windows)
5. Script Execution Analysis: Enable

# Data Collection Levels:
- Standard: Basic process/file/network events
- Enhanced: Adds command line, registry, module loads
- Maximum: Full behavioral telemetry (higher storage)`,
      note: "Higher collection levels increase storage consumption in Cortex Data Lake",
    },
    logToSyslog: {
      description: "Configure SIEM forwarding via Broker VM",
      example: `# Deploy Cortex XDR Broker VM
# Navigate to: Settings > Configurations > Broker VMs

# 1. Download and deploy Broker VM OVA
# 2. Configure Broker VM network settings
# 3. Register Broker VM with Cortex XDR tenant

# Configure Syslog Forwarding:
# Settings > Integrations > External Applications > Add Application

Syslog Target:
  - Server: <siem-ip>
  - Port: 514
  - Protocol: TCP/TLS
  - Format: CEF or LEEF

# Select data to forward:
  - Endpoint Events: Yes
  - Alerts: Yes
  - Incidents: Yes`,
    },
  },
  useCases: {
    operational: [
      {
        name: "Endpoint inventory",
        description: "Track all endpoints with XDR agents installed",
        fieldsUsed: ["endpoint_name", "endpoint_domain", "endpoint_os", "agent_version"],
        logic: "dataset=xdr_data | dedup endpoint_id | stats count by endpoint_os",
      },
      {
        name: "Agent health monitoring",
        description: "Monitor XDR agent connectivity and version status",
        fieldsUsed: ["endpoint_id", "endpoint_name", "agent_version", "event_timestamp"],
        logic: "dataset=endpoints | filter agent_status != CONNECTED",
      },
      {
        name: "Data collection verification",
        description: "Verify events are being collected from all endpoints",
        fieldsUsed: ["endpoint_id", "event_type", "event_timestamp"],
        logic: "dataset=xdr_data | stats count by endpoint_id, event_type | filter count < threshold",
      },
    ],
    security: [
      {
        name: "Suspicious PowerShell detection",
        description: "Detect encoded or obfuscated PowerShell commands",
        fieldsUsed: ["action_process_image_name", "action_process_command_line", "actor_primary_username"],
        logic: `event_type=PROCESS AND action_process_image_name="powershell.exe" AND action_process_command_line CONTAINS ANY ("-enc", "-ExecutionPolicy Bypass", "IEX", "DownloadString", "FromBase64")`,
      },
      {
        name: "LOLBIN execution monitoring",
        description: "Detect Living-off-the-Land binary abuse",
        fieldsUsed: ["action_process_image_name", "action_process_command_line", "actor_process_image_name"],
        logic: `event_type=PROCESS AND action_process_image_name IN ("certutil.exe", "mshta.exe", "regsvr32.exe", "rundll32.exe", "wmic.exe", "cscript.exe", "wscript.exe", "bitsadmin.exe")`,
      },
      {
        name: "Credential dumping detection",
        description: "Detect attempts to access LSASS or credential stores",
        fieldsUsed: ["action_process_image_name", "action_file_path", "event_sub_type"],
        logic: `(action_file_path CONTAINS "lsass" OR action_process_image_name IN ("mimikatz.exe", "procdump.exe", "comsvcs.dll")) AND event_type IN (PROCESS, FILE, INJECTION)`,
      },
      {
        name: "Lateral movement detection",
        description: "Detect remote execution tools and techniques",
        fieldsUsed: ["action_process_image_name", "action_remote_ip", "actor_primary_username"],
        logic: `event_type=PROCESS AND action_process_image_name IN ("psexec.exe", "wmic.exe", "winrm.cmd") AND action_remote_ip != null`,
      },
      {
        name: "Persistence mechanism detection",
        description: "Detect common persistence techniques",
        fieldsUsed: ["action_registry_key_name", "action_file_path", "event_sub_type"],
        logic: `(event_type=REGISTRY AND action_registry_key_name CONTAINS ANY ("Run", "RunOnce", "Services", "Winlogon")) OR (event_type=SCHEDULED_TASK)`,
      },
      {
        name: "Ransomware behavior detection",
        description: "Detect file encryption patterns",
        fieldsUsed: ["action_file_path", "action_file_name", "event_sub_type", "actor_process_image_name"],
        logic: `event_type=FILE AND event_sub_type IN (FILE_WRITE, FILE_RENAME) | stats count by actor_process_image_name, endpoint_id | filter count > 1000`,
      },
      {
        name: "C2 beaconing detection",
        description: "Detect regular network callbacks to suspicious destinations",
        fieldsUsed: ["action_remote_ip", "action_remote_port", "actor_process_image_name", "event_timestamp"],
        logic: `event_type=NETWORK | bin event_timestamp span=5m | stats count by action_remote_ip, actor_process_image_name | filter count > 50`,
      },
      {
        name: "Unsigned binary execution",
        description: "Monitor execution of unsigned or untrusted binaries",
        fieldsUsed: ["action_process_signature_status", "action_process_image_path", "action_process_image_sha256"],
        logic: `event_type=PROCESS AND action_process_signature_status IN (UNSIGNED, INVALID_SIGNATURE) AND action_process_image_path NOT CONTAINS "temp"`,
      },
    ],
    business: [
      {
        name: "Software usage tracking",
        description: "Track application usage across endpoints",
        fieldsUsed: ["action_process_image_name", "endpoint_name", "actor_primary_username"],
        logic: "event_type=PROCESS | stats dc(endpoint_id) as endpoints by action_process_image_name",
      },
      {
        name: "User activity monitoring",
        description: "Monitor user activities for compliance",
        fieldsUsed: ["actor_primary_username", "endpoint_name", "action_process_image_name", "event_timestamp"],
      },
      {
        name: "Endpoint security posture",
        description: "Report on endpoint security status for audits",
        fieldsUsed: ["endpoint_name", "endpoint_os", "agent_version", "action_process_signature_status"],
      },
    ],
  },
  troubleshooting: [
    {
      problem: "Events not appearing in Query Center",
      causes: [
        "Agent not connected to Cortex XDR",
        "Data collection profile not applied",
        "Network connectivity issues",
        "Agent in isolation mode",
      ],
      solutions: [
        "Check agent status in Endpoints page",
        "Verify endpoint is assigned to correct endpoint group with data collection profile",
        "Check agent can reach *.xdr.paloaltonetworks.com on port 443",
        "Review agent logs: C:\\ProgramData\\Cyvera\\Logs\\ (Windows)",
        "Ensure endpoint is not in isolation mode",
      ],
    },
    {
      problem: "Missing process command line data",
      causes: [
        "Data collection profile set to Standard",
        "Command line auditing not enabled on Windows",
        "Process started before agent initialized",
      ],
      solutions: [
        "Use Enhanced or Maximum data collection profile",
        "Enable Windows command line auditing via GPO",
        "Ensure XDR agent starts early in boot sequence",
      ],
    },
    {
      problem: "SIEM forwarding not working",
      causes: [
        "Broker VM not deployed or connected",
        "Incorrect syslog destination configuration",
        "Firewall blocking syslog traffic",
        "Wrong format selected (CEF vs LEEF)",
      ],
      solutions: [
        "Verify Broker VM status in Settings > Broker VMs",
        "Check syslog destination IP/port configuration",
        "Allow TCP/UDP 514 (or custom port) from Broker VM to SIEM",
        "Test with CEF format which has broader SIEM support",
      ],
    },
    {
      problem: "High volume of events causing storage issues",
      causes: [
        "Maximum data collection on all endpoints",
        "Noisy applications generating excessive events",
        "No event filtering configured",
      ],
      solutions: [
        "Use Standard or Enhanced collection for non-critical endpoints",
        "Create exclusions for known noisy applications",
        "Configure SIEM forwarding filters to send only relevant events",
        "Review and extend Data Lake retention policies",
      ],
    },
    {
      problem: "XQL queries timing out",
      causes: [
        "Query spans too large a time range",
        "Query returns too many results",
        "Complex query with multiple joins",
      ],
      solutions: [
        "Reduce time range or add more specific filters",
        "Use 'limit' clause to restrict results",
        "Simplify query by removing unnecessary fields",
        "Use 'sample' for initial exploration before full query",
      ],
    },
  ],
  testedOn: [
    {
      version: "8.2",
      os: "Cortex XDR Agent",
      testedBy: "admin",
      testedAt: "2026-01-03",
    },
    {
      version: "8.1",
      os: "Cortex XDR Agent",
      testedBy: "admin",
      testedAt: "2026-01-03",
    },
  ],
  contribution: {
    createdAt: "2026-01-03",
    createdBy: "admin",
    updatedAt: "2026-01-03",
    updatedBy: "admin",
    contributors: ["admin"],
    validated: false,
  },
};

export const cortexXdrAlerts: LogType = {
  id: "alerts",
  technologyId: "cortex-xdr",
  name: "Alerts",
  description: "Security alerts generated by Cortex XDR analytics engines, BIOC rules, and behavioral threat detection including malware, exploits, and suspicious activities",
  quickFacts: {
    defaultPathLinux: "Cortex XDR Console > Alerts",
    defaultPathDocker: "N/A - Cloud-based",
    defaultFormat: "JSON (via API) / CEF (via SIEM forwarding)",
    jsonNative: true,
    rotation: "Cloud-based retention (configurable)",
  },
  paths: {
    cloud: [
      {
        provider: "Cortex XDR Console",
        path: "Incident Response > Alerts",
      },
      {
        provider: "Cortex XDR API",
        path: "POST /public_api/v1/alerts/get_alerts",
      },
    ],
  },
  formats: [
    {
      id: "json",
      name: "JSON Format (API)",
      isDefault: true,
      structure: "Nested JSON with alert details, evidence, and related events",
      example: `{
  "alert_id": "12345",
  "external_id": "ALERT-2026-001",
  "severity": "HIGH",
  "name": "Behavioral Threat - Credential Dumping",
  "category": "Credential Access",
  "description": "Process attempted to access LSASS memory",
  "host_name": "WORKSTATION-01",
  "host_ip": "192.168.1.100",
  "user_name": "jsmith",
  "action_status": "BLOCKED",
  "detection_timestamp": 1704200000000,
  "mitre_tactic_id": "TA0006",
  "mitre_technique_id": "T1003.001",
  "causality_actor_process_image_name": "mimikatz.exe",
  "causality_actor_process_command_line": "mimikatz.exe sekurlsa::logonpasswords",
  "starred": false,
  "resolution_status": "NEW"
}`,
    },
  ],
  fields: [
    {
      name: "alert_id",
      type: "string",
      description: "Unique identifier for the alert",
      example: "12345",
    },
    {
      name: "external_id",
      type: "string",
      description: "Human-readable alert reference",
      example: "ALERT-2026-001",
    },
    {
      name: "severity",
      type: "string",
      description: "Alert severity level",
      example: "HIGH",
      enum: ["INFORMATIONAL", "LOW", "MEDIUM", "HIGH", "CRITICAL"],
    },
    {
      name: "name",
      type: "string",
      description: "Alert name/title",
      example: "Behavioral Threat - Credential Dumping",
    },
    {
      name: "category",
      type: "string",
      description: "MITRE ATT&CK tactic category",
      example: "Credential Access",
    },
    {
      name: "description",
      type: "string",
      description: "Detailed description of the alert",
      example: "Process attempted to access LSASS memory",
    },
    {
      name: "host_name",
      type: "string",
      description: "Affected endpoint hostname",
      example: "WORKSTATION-01",
    },
    {
      name: "host_ip",
      type: "ip",
      description: "IP address of affected endpoint",
      example: "192.168.1.100",
    },
    {
      name: "user_name",
      type: "string",
      description: "User associated with the alert",
      example: "jsmith",
    },
    {
      name: "action_status",
      type: "string",
      description: "Action taken by XDR agent",
      example: "BLOCKED",
      enum: ["DETECTED", "BLOCKED", "QUARANTINED", "REPORTED", "DISABLED"],
    },
    {
      name: "detection_timestamp",
      type: "integer",
      description: "Time the alert was generated",
      example: 1704200000000,
      unit: "milliseconds",
    },
    {
      name: "mitre_tactic_id",
      type: "string",
      description: "MITRE ATT&CK tactic identifier",
      example: "TA0006",
    },
    {
      name: "mitre_technique_id",
      type: "string",
      description: "MITRE ATT&CK technique identifier",
      example: "T1003.001",
    },
    {
      name: "resolution_status",
      type: "string",
      description: "Current investigation status",
      example: "NEW",
      enum: ["NEW", "UNDER_INVESTIGATION", "RESOLVED_THREAT_HANDLED", "RESOLVED_KNOWN_ISSUE", "RESOLVED_DUPLICATE", "RESOLVED_FALSE_POSITIVE", "RESOLVED_OTHER"],
    },
  ],
  parsing: {
    examples: {
      splunk: `# Cortex XDR Alerts in Splunk
index=cortex_xdr sourcetype="cortex:xdr:alerts"
| stats count by severity, category, action_status
| sort -count`,
    },
  },
  configuration: {
    enableLogging: {
      description: "Alerts are automatically generated based on detection rules",
      example: `# Configure alert forwarding
# Settings > Integrations > External Applications > Syslog

# Forward alerts to SIEM:
1. Create new Syslog integration
2. Select "Alerts" as data type
3. Configure SIEM destination`,
    },
  },
  useCases: {
    operational: [
      {
        name: "Alert volume monitoring",
        description: "Track daily alert counts and trends",
        fieldsUsed: ["severity", "detection_timestamp", "category"],
        logic: "stats count by severity, category | timechart",
      },
    ],
    security: [
      {
        name: "Alert triage",
        description: "Prioritize alerts by severity and category",
        fieldsUsed: ["severity", "category", "host_name", "user_name"],
        logic: "severity IN (HIGH, CRITICAL) | sort detection_timestamp desc",
      },
      {
        name: "MITRE ATT&CK mapping",
        description: "Track alerts by ATT&CK tactics and techniques",
        fieldsUsed: ["mitre_tactic_id", "mitre_technique_id", "name"],
        logic: "stats count by mitre_tactic_id, mitre_technique_id",
      },
    ],
    business: [
      {
        name: "Security posture reporting",
        description: "Report on alert status and resolution rates",
        fieldsUsed: ["resolution_status", "severity", "detection_timestamp"],
        logic: "stats count by resolution_status, severity",
      },
    ],
  },
  troubleshooting: [
    {
      problem: "Too many false positive alerts",
      causes: [
        "Overly sensitive BIOC rules",
        "Legitimate admin tools triggering alerts",
        "Missing exclusions for known applications",
      ],
      solutions: [
        "Review and tune BIOC rule thresholds",
        "Add process/path exclusions for legitimate tools",
        "Mark false positives to train analytics",
        "Create custom BIOC rules for environment-specific behavior",
      ],
    },
  ],
  testedOn: [
    {
      version: "8.2",
      os: "Cortex XDR",
      testedBy: "admin",
      testedAt: "2026-01-03",
    },
  ],
  contribution: {
    createdAt: "2026-01-03",
    createdBy: "admin",
    updatedAt: "2026-01-03",
    updatedBy: "admin",
    contributors: ["admin"],
    validated: false,
  },
};

export const logTypes: LogType[] = [cortexXdrEndpointEvents, cortexXdrAlerts];
